In [1]:
import pandas as pd

In [2]:
# df1 = [pd.read_csv('./raw_data/raw_data/sub_'+str(no)+'/fnirs_init.csv') for no in range(1, 98)]

In [3]:
df1 = [pd.read_csv('./raw_data/raw_data/sub_'+str(no)+'/fnirs_init.csv') for no in ['1',  '5', '7', '13', '14', '15', '20', '21', '22', '23', '24', '25', '27', '28', '29', '31', '32', '34', '35', '36', '37', '38', '40', '42', '43', '44', '45', '46', '47', '48', '49', '51', '52', '54', '55', '56', '57', '58', '60', '61', '62', '63', '64', '65', '68', '69', '70', '71', '72', '73', '74', '75', '76', '78', '79', '80', '81', '82', '83', '84', '85', '86', '91', '92', '93', '94', '95', '97']]

In [4]:
df1[34]

,row_index,timestamp,label,T,AC-A1,AC-A2,AC-A21,AC-A22,PH-A1,PH-A2,...,PH-C23,PH-C24,AC-D3,AC-D4,AC-D23,AC-D24,PH-D3,PH-D4,PH-D23,PH-D24
0,1043,1622304171496,-1,200.297,2647.0,225.1,5233.0,474.9,182.8,193.8,...,159.6,176.7,116.4,1954.0,127.2,3725.0,200.8,187.4,167.5,154.3
1,1044,1622304171563,-1,200.489,2662.0,226.2,5265.0,482.9,183.0,193.9,...,159.7,176.5,115.6,1959.0,128.1,3735.0,200.5,187.2,167.6,154.4
2,1045,1622304171629,-1,200.681,2691.0,231.8,5274.0,485.0,182.9,193.5,...,159.7,176.6,115.6,1970.0,128.0,3718.0,201.0,187.4,167.3,154.3
3,1046,1622304171695,-1,200.873,2671.0,230.2,5251.0,472.9,182.8,193.5,...,159.7,176.6,115.1,1963.0,127.4,3706.0,201.5,187.3,167.7,154.3
4,1047,1622304171761,-1,201.065,2658.0,225.0,5246.0,477.2,182.9,193.2,...,159.8,176.6,115.5,1951.0,127.4,3707.0,201.2,187.3,166.9,154.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,1143,1622304190428,-1,219.484,2474.0,223.5,5066.0,476.5,182.9,193.4,...,159.6,176.3,112.4,1956.0,126.8,3685.0,200.9,187.4,167.9,154.1
101,1144,1622304190494,-1,219.676,2478.0,227.5,5091.0,479.7,182.8,193.7,...,159.6,176.4,112.8,1957.0,128.8,3693.0,200.9,187.1,167.6,154.2
102,1145,1622304190560,-1,219.868,2505.0,232.6,5112.0,485.1,182.8,193.6,...,159.8,176.1,114.2,1963.0,130.3,3694.0,201.7,187.2,167.0,154.1
103,1146,1622304190626,-1,220.060,2528.0,238.5,5089.0,479.4,183.0,193.9,...,159.9,176.0,116.3,1971.0,127.7,3684.0,201.4,187.3,167.7,154.1
104,1147,1622304190692,-1,220.252,2466.0,227.9,5046.0,475.4,182.9,193.7,...,159.7,176.6,112.6,1952.0,126.4,3680.0,200.7,186.9,167.5,154.1

In [5]:
'1',  '5', '7', '13', '14', '15', '20', '21', '22', '23', '24', '25', '27', '28', '29', '31', '32', '34', '35', '36', '37', '38', '40', '42', '43', '44', '45', '46', '47', '48', '49', '51', '52', '54', '55', '56', '57', '58', '60', '61', '62', '63', '64', '65', '68', '69', '70', '71', '72', '73', '74', '75', '76', '78', '79', '80', '81', '82', '83', '84', '85', '86', '91', '92', '93', '94', '95', '97'

('1',
 '5',
 '7',
 '13',
 '14',
 '15',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '27',
 '28',
 '29',
 '31',
 '32',
 '34',
 '35',
 '36',
 '37',
 '38',
 '40',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '51',
 '52',
 '54',
 '55',
 '56',
 '57',
 '58',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '68',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '78',
 '79',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '91',
 '92',
 '93',
 '94',
 '95',
 '97')

In [6]:
data1 = pd.concat(df1, axis=0).sample(frac=1.0, random_state=123).reset_index(drop=True)

In [7]:
data1

,row_index,timestamp,label,T,AC-A1,AC-A2,AC-A21,AC-A22,PH-A1,PH-A2,...,PH-C23,PH-C24,AC-D3,AC-D4,AC-D23,AC-D24,PH-D3,PH-D4,PH-D23,PH-D24
0,1795,1624547768000,-1,344.707,2648.0,117.8,5249.0,364.1,295.40,303.40,...,339.20,351.8,83.19,2138.0,158.90,4148.0,111.60,97.82,79.06,65.41
1,4659,1618860824517,-1,3939.583,2723.0,418.4,5277.0,786.6,24.71,30.34,...,288.20,295.9,126.30,2399.0,76.39,4132.0,176.30,161.70,139.10,126.50
2,2086,1612805693353,-1,241.957,8873.0,4660.0,9974.0,9442.0,179.80,187.60,...,157.50,169.1,98.42,1901.0,154.40,3828.0,202.50,186.70,167.60,152.00
3,1809,1625077703541,-1,347.409,3743.0,348.5,5354.0,310.8,75.03,86.04,...,258.80,270.0,193.10,4393.0,116.20,3457.0,264.50,249.50,225.00,211.30
4,2030,1621277612031,-1,11558.890,2665.0,371.1,6268.0,816.0,175.10,187.60,...,136.90,148.4,175.00,2655.0,241.00,5684.0,194.20,178.30,160.40,144.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7147,1160,1623951999942,-1,8384.289,2274.0,193.6,4488.0,387.7,156.60,166.60,...,210.30,223.7,107.20,2248.0,107.80,3774.0,12.79,360.00,335.80,323.80
7148,1672,1622735898292,-1,321.103,3830.0,391.7,4164.0,392.7,168.50,175.40,...,94.16,108.7,349.90,5053.0,236.50,4309.0,143.30,130.60,109.50,96.83
7149,2049,1614095843961,-1,1696.543,4022.0,716.4,6367.0,1379.0,178.60,186.90,...,125.10,139.4,48.05,2269.0,50.29,4513.0,195.50,183.80,158.90,148.40
7150,2803,1621869973317,-1,539.880,3062.0,309.4,5961.0,443.6,181.00,189.50,...,138.20,148.7,132.60,3591.0,138.30,5766.0,203.00,187.90,168.40,153.60
7151,2392,1622133447520,-1,2324.995,3785.0,254.5,6097.0,694.9,179.30,188.20,...,143.40,152.9,234.00,2754.0,355.00,6101.0,197.60,178.30,163.90,145.20

In [8]:
df2 = [pd.read_csv('./raw_data/raw_data/sub_'+str(no)+'/fnirs_test.csv') for no in ['1',  '5', '7', '13', '14', '15', '20', '21', '22', '23', '24', '25', '27', '28', '29', '31', '32', '34', '35', '36', '37', '38', '40', '42', '43', '44', '45', '46', '47', '48', '49', '51', '52', '54', '55', '56', '57', '58', '60', '61', '62', '63', '64', '65', '68', '69', '70', '71', '72', '73', '74', '75', '76', '78', '79', '80', '81', '82', '83', '84', '85', '86', '91', '92', '93', '94', '95', '97']]

In [9]:
df2[4]

,row_index,timestamp,label,T,AC-A1,AC-A2,AC-A21,AC-A22,PH-A1,PH-A2,...,PH-C23,PH-C24,AC-D3,AC-D4,AC-D23,AC-D24,PH-D3,PH-D4,PH-D23,PH-D24
0,0,1611091095938,-1,2261.592,2374.0,519.8,6533.0,1339.0,177.3,184.0,...,5.777,17.35,91.36,1715.0,160.6,3800.0,206.0,190.7,172.1,158.2
1,1,1611091096006,-1,2261.784,2413.0,532.0,6588.0,1358.0,177.3,184.2,...,5.579,16.78,91.89,1729.0,163.1,3815.0,205.7,190.6,172.4,158.1
2,2,1611091096085,-1,2261.976,2443.0,547.3,6461.0,1348.0,177.5,184.5,...,5.695,16.83,95.61,1746.0,159.3,3802.0,206.0,190.7,171.6,158.3
3,3,1611091096141,-1,2262.168,2379.0,521.6,6465.0,1322.0,177.4,184.4,...,5.634,17.32,90.81,1714.0,158.6,3774.0,205.4,190.6,172.0,158.1
4,4,1611091096217,-1,2262.360,2352.0,512.2,6479.0,1337.0,177.6,184.3,...,5.591,17.14,90.39,1705.0,160.5,3779.0,205.8,190.5,172.4,158.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3054,3054,1611091682055,2,2848.089,2382.0,495.6,6054.0,1276.0,177.5,183.6,...,5.326,16.72,90.94,1604.0,158.6,3412.0,205.2,190.0,171.8,157.3
3055,3055,1611091682122,2,2848.281,2304.0,470.6,6019.0,1268.0,177.0,183.9,...,5.435,16.77,85.69,1544.0,157.7,3408.0,205.7,190.0,171.0,157.4
3056,3056,1611091682188,2,2848.473,2300.0,463.0,5988.0,1274.0,176.9,184.0,...,5.416,16.51,85.90,1544.0,163.1,3430.0,205.4,189.9,171.6,157.4
3057,3057,1611091682255,2,2848.665,2339.0,471.4,5999.0,1288.0,176.9,184.0,...,5.599,16.60,90.14,1572.0,171.1,3485.0,205.1,190.0,171.5,157.5
3058,3058,1611091682322,2,2848.857,2364.0,486.2,5993.0,1304.0,177.4,184.0,...,5.525,16.34,94.47,1599.0,170.5,3488.0,206.8,189.9,171.6,157.5

In [10]:
data2 = pd.concat(df2, axis=0).sample(frac=1.0, random_state=123).reset_index(drop=True)

In [11]:
data2

,row_index,timestamp,label,T,AC-A1,AC-A2,AC-A21,AC-A22,PH-A1,PH-A2,...,PH-C23,PH-C24,AC-D3,AC-D4,AC-D23,AC-D24,PH-D3,PH-D4,PH-D23,PH-D24
0,2223,1613423551213,1,3336.920,2164.0,469.2,6017.0,1164.0,155.2,165.0,...,87.70,101.50,69.77,1389.0,115.70,3361.0,215.4,200.7,181.10,166.60
1,2978,1611436455708,-1,2738.926,4509.0,531.5,6685.0,568.3,176.5,186.7,...,179.40,196.70,158.10,4205.0,133.60,5866.0,170.7,159.8,131.40,122.10
2,1495,1617313476890,-1,7509.196,1984.0,215.6,4263.0,433.2,181.8,187.9,...,277.60,290.00,110.20,2006.0,223.20,4168.0,102.9,89.0,68.02,55.09
3,2389,1612820928579,2,3185.933,2240.0,135.4,4901.0,366.5,287.0,291.2,...,92.39,105.00,102.00,1891.0,132.30,4645.0,199.6,183.9,164.80,150.00
4,1329,1626276316002,0,2561.651,3764.0,223.6,5119.0,509.8,155.8,165.5,...,301.90,319.50,93.09,1984.0,116.60,5470.0,156.0,145.1,120.40,110.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211284,955,1622738041744,-1,2464.662,3115.0,382.0,2579.0,500.7,166.1,172.5,...,92.72,106.70,296.00,4819.0,223.40,4108.0,142.4,127.7,108.30,94.30
211285,2846,1625163688330,-1,2515.967,2969.0,167.4,3036.0,607.9,326.4,332.1,...,42.60,52.63,250.00,2562.0,389.00,5675.0,281.3,265.9,248.60,233.40
211286,2305,1611436326640,1,2609.704,4612.0,531.4,6785.0,575.3,176.8,186.2,...,179.70,195.60,151.50,4242.0,103.10,5876.0,169.1,159.4,130.00,121.80
211287,293,1612990397630,3,15639.620,2057.0,224.9,5204.0,458.0,189.8,196.9,...,145.10,156.60,54.82,1992.0,72.93,3706.0,194.5,181.7,156.60,146.20
211288,300,1611435941184,3,2224.654,4333.0,507.4,6126.0,536.0,176.9,186.4,...,180.00,195.80,148.10,4204.0,66.79,5462.0,169.8,159.5,132.80,121.80

In [12]:
data1['label'].value_counts()

-1    7152
Name: label, dtype: int64

In [13]:
data2['label'].value_counts()

-1    54108
 3    43652
 2    40144
 0    36700
 1    36685
Name: label, dtype: int64

In [14]:
data1.describe()

,row_index,timestamp,label,T,AC-A1,AC-A2,AC-A21,AC-A22,PH-A1,PH-A2,...,PH-C23,PH-C24,AC-D3,AC-D4,AC-D23,AC-D24,PH-D3,PH-D4,PH-D23,PH-D24
count,7152.000000,7.152000e+03,7152.0,7152.000000,7152.000000,7152.000000,7152.000000,7152.000000,7152.000000,7152.000000,...,7152.000000,7152.000000,7152.000000,7152.000000,7152.000000,7152.000000,7152.000000,7152.000000,7152.000000,7152.000000
mean,2165.738395,1.620200e+12,-1.0,2753.503408,3085.056306,439.607665,5352.691415,865.321546,183.417371,187.771363,...,156.027566,162.813829,139.322254,2714.651706,182.618294,4682.270694,185.639422,178.679213,178.849254,179.569625
std,1511.639675,5.434540e+09,0.0,4620.000250,1470.109880,574.903398,1217.596941,1213.660111,79.636728,79.350804,...,92.100934,90.725954,69.485648,1128.874526,96.831871,927.970326,82.738063,82.154249,82.924725,82.311731
min,103.000000,1.605027e+12,-1.0,158.440000,924.000000,46.230000,2110.000000,102.600000,0.006908,7.297000,...,0.116900,1.039000,10.120000,1212.000000,6.956000,2688.000000,1.719000,0.003122,0.009870,15.850000
25%,1146.000000,1.615657e+12,-1.0,312.019000,2153.000000,168.200000,4627.500000,384.675000,156.700000,164.675000,...,93.712500,104.300000,98.890000,1990.000000,113.350000,4082.750000,149.000000,144.100000,130.575000,135.600000
50%,1676.000000,1.622133e+12,-1.0,571.800000,2649.000000,283.200000,5244.000000,488.550000,180.900000,188.700000,...,144.400000,154.400000,128.300000,2366.000000,159.400000,4554.500000,196.600000,184.600000,167.500000,156.200000
75%,2606.000000,1.624042e+12,-1.0,2071.629000,3872.000000,535.300000,6017.000000,1073.000000,217.100000,214.800000,...,212.075000,223.325000,167.625000,3055.000000,242.500000,5401.000000,233.050000,223.900000,225.500000,218.400000
max,7556.000000,1.627060e+12,-1.0,19584.790000,9709.000000,5140.000000,10840.000000,10280.000000,360.000000,353.500000,...,348.000000,352.200000,403.300000,7457.000000,428.100000,7837.000000,342.900000,360.000000,360.000000,357.800000

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [16]:
scaler.fit(data2)

StandardScaler()

In [ ]:
data2.describe()