In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import tensorflow as tf

In [2]:
df = [pd.read_csv('./size_30sec_150ts_stride_03ts/sub_'+str(no)+'.csv') for no in ['1',  '5', '7', '13', '14', '15', '20', '21', '22', '23']]

In [19]:
df[3]

,AB_I_O,AB_PHI_O,AB_I_DO,AB_PHI_DO,CD_I_O,CD_PHI_O,CD_I_DO,CD_PHI_DO,chunk,label
0,0.783289,0.349782,0.203207,0.061833,-2.121523,-1.329327,0.611741,3.364802,0,0
1,0.760787,0.342344,0.217197,0.098421,-2.122762,-0.978403,0.595027,3.042482,0,0
2,0.733985,0.341725,0.230654,0.138154,-2.114932,-0.646085,0.572121,2.737796,0,0
3,0.702244,0.346367,0.243391,0.179775,-2.099097,-0.338552,0.544212,2.452826,0,0
4,0.665033,0.354683,0.255203,0.221814,-2.076874,-0.061226,0.513051,2.189334,0,0
...,...,...,...,...,...,...,...,...,...,...
223195,1.661890,0.360775,-0.005979,-0.343756,0.748391,-2.292206,0.237663,1.480709,1487,2
223196,1.673887,0.317069,-0.011467,-0.344822,0.749684,-2.591031,0.242524,1.500127,1487,2
223197,1.683358,0.271503,-0.015906,-0.343387,0.759199,-2.857547,0.244660,1.516918,1487,2
223198,1.690513,0.228735,-0.019308,-0.340939,0.777910,-3.074144,0.243919,1.529231,1487,2
223199,1.695630,0.193651,-0.021699,-0.339110,0.806172,-3.222889,0.240315,1.534429,1487,2

In [4]:
data = pd.concat(df, axis=0).sample(frac=1.0, random_state=123).reset_index(drop=True)

In [5]:
data

,AB_I_O,AB_PHI_O,AB_I_DO,AB_PHI_DO,CD_I_O,CD_PHI_O,CD_I_DO,CD_PHI_DO,chunk,label
0,0.663188,0.389715,-0.185006,0.120750,2.232674,1.923699,-0.593878,-0.950375,475,2
1,-0.079515,0.717639,-0.050393,-0.058826,1.276240,1.603060,-0.159616,-0.605578,786,2
2,-0.060867,-0.279108,-0.022495,0.014755,-0.243407,0.395337,0.159221,0.018009,545,2
3,-0.322999,-0.139480,0.192401,0.166977,1.564911,1.018649,-0.326780,0.285423,1226,0
4,-0.550518,-0.685657,0.164663,0.364372,-0.168589,0.567829,-0.174812,-0.278690,130,1
...,...,...,...,...,...,...,...,...,...,...
2231995,0.909855,-0.081555,-0.219605,-0.418863,0.895829,0.032883,-0.760300,0.350728,1128,3
2231996,-0.075609,0.168641,-0.023010,-0.109849,-0.516948,-1.202438,-0.006731,0.236140,833,2
2231997,-0.096547,0.947392,0.110562,-0.269774,1.728597,0.181823,0.066651,-0.298664,186,2
2231998,0.015857,0.119944,-0.021443,-0.003080,0.545062,-0.127643,-0.082148,0.107436,364,3
2231999,0.226142,0.025575,-0.205006,-0.012939,-0.220851,-5.717789,0.437039,3.014176,693,0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2232000 entries, 0 to 2231999
Data columns (total 10 columns):
 #   Column     Dtype
---  ------     -----
 0   AB_I_O     float64
 1   AB_PHI_O   float64
 2   AB_I_DO    float64
 3   AB_PHI_DO  float64
 4   CD_I_O     float64
 5   CD_PHI_O   float64
 6   CD_I_DO    float64
 7   CD_PHI_DO  float64
 8   chunk      int64
 9   label      int64
dtypes: float64(8), int64(2)
memory usage: 170.3 MB

In [7]:
data.describe()

,AB_I_O,AB_PHI_O,AB_I_DO,AB_PHI_DO,CD_I_O,CD_PHI_O,CD_I_DO,CD_PHI_DO,chunk,label
count,2.232000e+06,2.232000e+06,2.232000e+06,2.232000e+06,2.232000e+06,2.232000e+06,2.232000e+06,2.232000e+06,2.232000e+06,2.232000e+06
mean,1.136735e-01,3.920088e-02,-4.773474e-02,-3.424626e-02,1.974274e-01,3.910633e-02,-4.719540e-02,1.248183e-02,7.435000e+02,1.500000e+00
std,6.839449e-01,6.790479e-01,2.979168e-01,3.086871e-01,8.692754e-01,9.998830e-01,3.609556e-01,5.714333e-01,4.295486e+02,1.118034e+00
min,-4.100853e+00,-3.634505e+00,-2.038598e+00,-1.689752e+00,-4.933232e+00,-6.554512e+00,-2.678691e+00,-4.866796e+00,0.000000e+00,0.000000e+00
25%,-2.842235e-01,-3.877954e-01,-2.004464e-01,-2.174479e-01,-3.214917e-01,-4.819492e-01,-2.440746e-01,-2.690165e-01,3.717500e+02,7.500000e-01
50%,1.078718e-01,4.310820e-02,-3.481962e-02,-3.253520e-02,1.915897e-01,6.316408e-02,-5.273332e-02,-2.259944e-02,7.435000e+02,1.500000e+00
75%,5.250921e-01,4.689479e-01,1.172713e-01,1.534015e-01,6.952320e-01,6.110315e-01,1.451842e-01,2.285080e-01,1.115250e+03,2.250000e+00
max,3.858700e+00,2.829062e+00,1.248731e+00,1.671624e+00,3.601769e+00,7.597507e+00,2.150336e+00,5.524194e+00,1.487000e+03,3.000000e+00

In [8]:
def onehot_encode(df, column):
    df = df.copy()
    dummies = pd.get_dummies(df[column], prefix=column)
    df = pd.concat([df, dummies], axis=1)
    df = df.drop(column, axis=1)
    return df

In [9]:
onehot_encode(data, column='label')

,AB_I_O,AB_PHI_O,AB_I_DO,AB_PHI_DO,CD_I_O,CD_PHI_O,CD_I_DO,CD_PHI_DO,chunk,label_0,label_1,label_2,label_3
0,0.663188,0.389715,-0.185006,0.120750,2.232674,1.923699,-0.593878,-0.950375,475,0,0,1,0
1,-0.079515,0.717639,-0.050393,-0.058826,1.276240,1.603060,-0.159616,-0.605578,786,0,0,1,0
2,-0.060867,-0.279108,-0.022495,0.014755,-0.243407,0.395337,0.159221,0.018009,545,0,0,1,0
3,-0.322999,-0.139480,0.192401,0.166977,1.564911,1.018649,-0.326780,0.285423,1226,1,0,0,0
4,-0.550518,-0.685657,0.164663,0.364372,-0.168589,0.567829,-0.174812,-0.278690,130,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2231995,0.909855,-0.081555,-0.219605,-0.418863,0.895829,0.032883,-0.760300,0.350728,1128,0,0,0,1
2231996,-0.075609,0.168641,-0.023010,-0.109849,-0.516948,-1.202438,-0.006731,0.236140,833,0,0,1,0
2231997,-0.096547,0.947392,0.110562,-0.269774,1.728597,0.181823,0.066651,-0.298664,186,0,0,1,0
2231998,0.015857,0.119944,-0.021443,-0.003080,0.545062,-0.127643,-0.082148,0.107436,364,0,0,0,1
2231999,0.226142,0.025575,-0.205006,-0.012939,-0.220851,-5.717789,0.437039,3.014176,693,1,0,0,0

In [10]:
data['chunk'].value_counts()

475     1500
828     1500
611     1500
296     1500
670     1500
        ...
528     1500
891     1500
914     1500
1214    1500
839     1500
Name: chunk, Length: 1488, dtype: int64

In [11]:
def preprocess_inputs(df):
    df = df.copy()
    
    
    # Split df into X and y
    y = df['label'].copy()
    X = df.drop('label', axis=1)
    
    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=123)
    
    # Scale X with a standard scaler
    scaler = StandardScaler()
    scaler.fit(X_train)
    
    X_train = pd.DataFrame(scaler.transform(X_train), columns=X.columns)
    X_test = pd.DataFrame(scaler.transform(X_test), columns=X.columns)
    
    return X_train, X_test, y_train, y_test

In [12]:
X_train, X_test, y_train, y_test = preprocess_inputs(data)

In [13]:
X_train

,AB_I_O,AB_PHI_O,AB_I_DO,AB_PHI_DO,CD_I_O,CD_PHI_O,CD_I_DO,CD_PHI_DO,chunk
0,-0.610963,-0.276473,1.429095,0.501739,-1.145118,-0.512540,0.958565,0.593366,-0.397695
1,-0.641249,-0.430084,0.747949,0.105238,-0.061200,0.502598,0.153372,-0.390477,0.712976
2,0.636422,0.032222,-1.045399,-1.052766,1.043777,1.229900,-1.310945,-0.618052,-0.970495
3,-1.439172,-1.364385,2.749922,0.563012,-2.546144,-2.242353,2.891313,1.542224,1.118127
4,0.717698,-0.583291,-0.215802,-1.363502,0.677012,0.821570,-1.068716,-0.815691,-1.366332
...,...,...,...,...,...,...,...,...,...
1562395,0.860201,0.131896,-0.494145,-0.635775,0.554273,1.684364,0.141931,-1.312004,-1.517681
1562396,-0.970612,-1.067017,0.712760,1.290140,-0.421394,0.528212,-0.352891,-0.509202,-1.375645
1562397,0.136944,1.211176,0.157037,-0.438400,-0.887759,-0.843222,0.925590,0.234335,-0.053084
1562398,-0.507651,-0.543724,0.105456,0.991647,-0.481548,-0.012837,-0.131946,-0.590920,-1.312777
1562399,-0.594778,-1.170200,0.924976,1.412689,-0.581683,0.177991,0.197809,-0.342462,-1.312777

In [14]:
y_train

876541     3
1672042    1
1194678    3
1215414    0
1753890    1
          ..
1954914    0
1241052    1
28030      0
277869     1
773630     1
Name: label, Length: 1562400, dtype: int64

In [15]:
y_train.value_counts()

2    390664
3    390644
1    390621
0    390471
Name: label, dtype: int64

In [16]:
def build_model(num_classes=4):
    
    inputs = tf.keras.Input(shape=(X_train.shape[1],))
    x = tf.keras.layers.Dense(128, activation='relu')(inputs)
    x = tf.keras.layers.Dense(128, activation='relu')(x)
    outputs = tf.keras.layers.Dense(num_classes, activation='softmax')(x)
    
    model = tf.keras.Model(inputs=inputs, outputs=outputs)
    
    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    
    return model

In [17]:
label_model = build_model(num_classes=4)

label_history = label_model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    batch_size=32,
    epochs=50,
    callbacks=[
        tf.keras.callbacks.EarlyStopping(
            monitor='val_loss',
            patience=3,
            restore_best_weights=True
        )
    ]
)

Epoch 1/50
39060/39060 [==============================] - 69s 2ms/step - loss: 0.1337 - accuracy: 0.9506 - val_loss: 0.0391 - val_accuracy: 0.9860
Epoch 2/50
39060/39060 [==============================] - 68s 2ms/step - loss: 0.0286 - accuracy: 0.9901 - val_loss: 0.0285 - val_accuracy: 0.9895
Epoch 3/50
39060/39060 [==============================] - 68s 2ms/step - loss: 0.0225 - accuracy: 0.9924 - val_loss: 0.0181 - val_accuracy: 0.9940
Epoch 4/50
39060/39060 [==============================] - 62s 2ms/step - loss: 0.0190 - accuracy: 0.9938 - val_loss: 0.0088 - val_accuracy: 0.9971
Epoch 5/50
39060/39060 [==============================] - 62s 2ms/step - loss: 0.0163 - accuracy: 0.9948 - val_loss: 0.0170 - val_accuracy: 0.9945
Epoch 6/50
39060/39060 [==============================] - 62s 2ms/step - loss: 0.0152 - accuracy: 0.9953 - val_loss: 0.0065 - val_accuracy: 0.9980
Epoch 7/50
39060/39060 [==============================] - 67s 2ms/step - loss: 0.0138 - accuracy: 0.9957 - val_loss: 0.0386 - val_accuracy: 0.9904
Epoch 8/50
39060/39060 [==============================] - 65s 2ms/step - loss: 0.0129 - accuracy: 0.9962 - val_loss: 0.0105 - val_accuracy: 0.9966
Epoch 9/50
39060/39060 [==============================] - 67s 2ms/step - loss: 0.0120 - accuracy: 0.9964 - val_loss: 0.0122 - val_accuracy: 0.9961

In [20]:
class_acc = class_model.evaluate(X_test, y_test, verbose=0)[1]
print("Test Accuracy: {:.2f}%".format(class_acc * 100))

Test Accuracy: 99.80%