In [1]:
import pandas as pd

In [4]:
df = [pd.read_csv('./size_30sec_150ts_stride_03ts/sub_'+str(no)+'.csv') for no in ['1',  '5', '7', '13', '14', '15', '20', '21', '22', '23', '24', '25', '27', '28', '29', '31', '32', '34', '35', '36', '37', '38', '40', '42', '43', '44', '45', '46', '47', '48', '49', '51', '52', '54', '55', '56', '57', '58', '60', '61', '62', '63', '64', '65', '68', '69', '70', '71', '72', '73', '74', '75', '76', '78', '79', '80', '81', '82', '83', '84', '85', '86', '91', '92', '93', '94', '95', '97']]

In [6]:
df[3]

,AB_I_O,AB_PHI_O,AB_I_DO,AB_PHI_DO,CD_I_O,CD_PHI_O,CD_I_DO,CD_PHI_DO,chunk,label
0,0.783289,0.349782,0.203207,0.061833,-2.121523,-1.329327,0.611741,3.364802,0,0
1,0.760787,0.342344,0.217197,0.098421,-2.122762,-0.978403,0.595027,3.042482,0,0
2,0.733985,0.341725,0.230654,0.138154,-2.114932,-0.646085,0.572121,2.737796,0,0
3,0.702244,0.346367,0.243391,0.179775,-2.099097,-0.338552,0.544212,2.452826,0,0
4,0.665033,0.354683,0.255203,0.221814,-2.076874,-0.061226,0.513051,2.189334,0,0
...,...,...,...,...,...,...,...,...,...,...
223195,1.661890,0.360775,-0.005979,-0.343756,0.748391,-2.292206,0.237663,1.480709,1487,2
223196,1.673887,0.317069,-0.011467,-0.344822,0.749684,-2.591031,0.242524,1.500127,1487,2
223197,1.683358,0.271503,-0.015906,-0.343387,0.759199,-2.857547,0.244660,1.516918,1487,2
223198,1.690513,0.228735,-0.019308,-0.340939,0.777910,-3.074144,0.243919,1.529231,1487,2
223199,1.695630,0.193651,-0.021699,-0.339110,0.806172,-3.222889,0.240315,1.534429,1487,2

In [7]:
data = pd.concat(df, axis=0).sample(frac=1.0, random_state=123).reset_index(drop=True)

In [8]:
data

,AB_I_O,AB_PHI_O,AB_I_DO,AB_PHI_DO,CD_I_O,CD_PHI_O,CD_I_DO,CD_PHI_DO,chunk,label
0,1.323759,0.227600,0.038483,0.158088,1.246948,0.413082,0.007069,-0.027696,1484,2
1,-0.022784,-0.720817,-0.197396,0.602230,1.688199,3.401558,0.283809,-2.807081,635,3
2,-0.253427,-0.546414,0.064562,-0.076911,-0.338436,1.032295,0.055719,-0.186550,810,2
3,0.616833,1.236132,0.062210,-0.134666,0.197761,-0.631392,0.179321,0.186758,527,2
4,-0.609480,-0.496504,-0.068751,0.288685,-0.166358,-0.821917,-0.111499,-0.182476,1133,3
...,...,...,...,...,...,...,...,...,...,...
15177595,-0.075609,0.168641,-0.023010,-0.109849,-0.516948,-1.202438,-0.006731,0.236140,833,2
15177596,-1.481295,0.443138,-1.355720,0.306013,-0.717651,0.708136,-1.087945,0.015203,1125,3
15177597,0.019262,-0.968455,0.301510,0.290383,-0.079807,0.442778,0.355068,-0.016769,1364,1
15177598,-1.775998,-0.627331,0.919883,0.380983,-1.407088,-1.262267,0.663006,1.225582,1232,0
15177599,-0.352555,-0.414627,0.135240,0.322743,-0.113031,-0.869999,0.010943,-0.139069,383,1

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15177600 entries, 0 to 15177599
Data columns (total 10 columns):
 #   Column     Dtype
---  ------     -----
 0   AB_I_O     float64
 1   AB_PHI_O   float64
 2   AB_I_DO    float64
 3   AB_PHI_DO  float64
 4   CD_I_O     float64
 5   CD_PHI_O   float64
 6   CD_I_DO    float64
 7   CD_PHI_DO  float64
 8   chunk      int64
 9   label      int64
dtypes: float64(8), int64(2)
memory usage: 1.1 GB

In [10]:
data.describe()

,AB_I_O,AB_PHI_O,AB_I_DO,AB_PHI_DO,CD_I_O,CD_PHI_O,CD_I_DO,CD_PHI_DO,chunk,label
count,1.517760e+07,1.517760e+07,1.517760e+07,1.517760e+07,1.517760e+07,1.517760e+07,1.517760e+07,1.517760e+07,1.517760e+07,1.517760e+07
mean,8.735127e-02,3.297893e-02,-2.060717e-02,-1.777929e-02,1.618290e-01,2.121132e-02,-4.030520e-02,7.540065e-03,7.435000e+02,1.500000e+00
std,7.721446e-01,7.188164e-01,3.492425e-01,3.277457e-01,8.495922e-01,3.764963e+00,4.110466e-01,4.614332e+00,4.295485e+02,1.118034e+00
min,-6.429749e+00,-5.979288e+00,-3.030644e+00,-3.769702e+00,-6.843432e+00,-1.449689e+02,-4.518623e+00,-1.005990e+02,0.000000e+00,0.000000e+00
25%,-2.731426e-01,-4.056388e-01,-1.948475e-01,-2.084876e-01,-2.852982e-01,-4.775214e-01,-2.477120e-01,-2.726524e-01,3.717500e+02,7.500000e-01
50%,8.700932e-02,3.428208e-02,-2.377352e-02,-2.086407e-02,1.540354e-01,6.696880e-02,-5.207437e-02,-3.776323e-02,7.435000e+02,1.500000e+00
75%,4.523924e-01,4.689659e-01,1.526836e-01,1.703553e-01,5.959714e-01,6.079405e-01,1.507761e-01,1.986567e-01,1.115250e+03,2.250000e+00
max,1.019324e+01,5.866892e+00,5.588680e+00,2.660335e+00,8.819619e+00,1.470710e+02,5.069249e+00,1.960461e+02,1.487000e+03,3.000000e+00

In [11]:
def onehot_encode(df, column):
    df = df.copy()
    dummies = pd.get_dummies(df[column], prefix=column)
    df = pd.concat([df, dummies], axis=1)
    df = df.drop(column, axis=1)
    return df

In [12]:
onehot_encode(data, column='label')

,AB_I_O,AB_PHI_O,AB_I_DO,AB_PHI_DO,CD_I_O,CD_PHI_O,CD_I_DO,CD_PHI_DO,chunk,label_0,label_1,label_2,label_3
0,1.323759,0.227600,0.038483,0.158088,1.246948,0.413082,0.007069,-0.027696,1484,0,0,1,0
1,-0.022784,-0.720817,-0.197396,0.602230,1.688199,3.401558,0.283809,-2.807081,635,0,0,0,1
2,-0.253427,-0.546414,0.064562,-0.076911,-0.338436,1.032295,0.055719,-0.186550,810,0,0,1,0
3,0.616833,1.236132,0.062210,-0.134666,0.197761,-0.631392,0.179321,0.186758,527,0,0,1,0
4,-0.609480,-0.496504,-0.068751,0.288685,-0.166358,-0.821917,-0.111499,-0.182476,1133,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15177595,-0.075609,0.168641,-0.023010,-0.109849,-0.516948,-1.202438,-0.006731,0.236140,833,0,0,1,0
15177596,-1.481295,0.443138,-1.355720,0.306013,-0.717651,0.708136,-1.087945,0.015203,1125,0,0,0,1
15177597,0.019262,-0.968455,0.301510,0.290383,-0.079807,0.442778,0.355068,-0.016769,1364,0,1,0,0
15177598,-1.775998,-0.627331,0.919883,0.380983,-1.407088,-1.262267,0.663006,1.225582,1232,1,0,0,0
15177599,-0.352555,-0.414627,0.135240,0.322743,-0.113031,-0.869999,0.010943,-0.139069,383,0,1,0,0

In [13]:
data['chunk'].value_counts()

1484    10200
1298    10200
418     10200
866     10200
681     10200
        ...
241     10200
849     10200
1249    10200
53      10200
1329    10200
Name: chunk, Length: 1488, dtype: int64

In [18]:
def preprocess_inputs(df, target='label'):
    df = df.copy()
    
    # One-hot encode whichever target column is not being used
#     targets = ['Class', 'User']
#     targets.remove(target)
    df = onehot_encode(df, column=target)
    
    # Split df into X and y
    y = df[target].copy()
    X = df.drop(target, axis=1)
    
    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=123)
    
    # Scale X with a standard scaler
    scaler = StandardScaler()
    scaler.fit(X_train)
    
    X_train = pd.DataFrame(scaler.transform(X_train), columns=X.columns)
    X_test = pd.DataFrame(scaler.transform(X_test), columns=X.columns)
    
    return X_train, X_test, y_train, y_test

In [ ]:
X_train, X_test, y_train, y_test = preprocess_inputs(data, target='label')